export interface Theme {
  id: string;
  name: string;
  type: "light" | "dark";
  tokens: Record<string, string>;
}

const sharedShadcnMapping = {
  "--foreground": "var(--text)",
  "--primary": "var(--element-selected)",
  "--primary-foreground": "var(--background)",
  "--secondary": "var(--element-background)",
  "--secondary-foreground": "var(--text)",
  "--muted": "var(--element-background)",
  "--muted-foreground": "var(--text-muted)",
  "--accent": "var(--ghost-element-hover)",
  "--accent-foreground": "var(--text)",
  "--destructive": "var(--error)",
  "--destructive-foreground": "var(--background)",
  "--card": "var(--surface)",
  "--card-foreground": "var(--text)",
  "--popover": "var(--surface-elevated)",
  "--popover-foreground": "var(--text)",
  "--input": "var(--border-variant)",
  "--ring": "var(--border-focused)",

  // Legacy aliases
  "--surface-canvas": "var(--app-chrome-background)",
  "--surface-subtle": "var(--editor-background)",
  "--surface-strong": "var(--element-background)",
};

export const THEMES: Record<string, Theme> = {
  light: {
    id: "light",
    name: "Light",
    type: "light",
    tokens: {
      "--background": "#f5f5f5",
      "--surface": "#f5f5f5",
      "--surface-elevated": "#f7f7f7",
      "--editor-background": "#ffffff",
      "--app-chrome-background": "#f5f5f5",
      "--text": "#0a0a0a",
      "--text-muted": "#737373",
      "--text-placeholder": "#8a8a8a",
      "--text-disabled": "#8a8a8a",
      "--text-accent": "#009fff",
      "--icon": "#525252",
      "--icon-muted": "#737373",
      "--icon-disabled": "#8a8a8a",
      "--icon-placeholder": "#8a8a8a",
      "--icon-accent": "#009fff",
      "--border": "#d4d4d4",
      "--border-variant": "#e5e5e5",
      "--border-focused": "#009fff",
      "--border-selected": "#009fff",
      "--border-disabled": "#d4d4d4",
      "--element-background": "#ededed",
      "--element-hover": "#dfebff80",
      "--element-active": "#dfebffb3",
      "--element-selected": "#dfebffcc",
      "--element-disabled": "#ededed80",
      "--ghost-element-background": "transparent",
      "--ghost-element-hover": "#dfebff59",
      "--ghost-element-active": "#dfebff8c",
      "--ghost-element-selected": "#dfebffa6",
      "--ghost-element-disabled": "transparent",
      "--scrollbar-thumb": "#8a8a8a4d",
      "--scrollbar-thumb-hover": "#8a8a8a80",
      "--scrollbar-track": "transparent",
      "--error": "#d52c36",
      "--error-background": "#d52c361a",
      "--error-border": "#d52c364d",
      "--warning": "#009fff",
      "--warning-background": "#009fff1a",
      "--warning-border": "#009fff4d",
      "--success": "#18a46c",
      "--success-background": "#18a46c1a",
      "--success-border": "#18a46c4d",
      "--info": "#1ca1c7",
      "--info-background": "#1ca1c71a",
      "--info-border": "#1ca1c74d",
      "--conflict": "#693acf",
      "--conflict-background": "#693acf1a",
      "--conflict-border": "#693acf4d",
      "--created": "#18a46c",
      "--created-background": "#18a46c1a",
      "--created-border": "#18a46c4d",
      "--modified": "#009fff",
      "--modified-background": "#009fff1a",
      "--modified-border": "#009fff4d",
      "--deleted": "#d52c36",
      "--deleted-background": "#d52c361a",
      "--deleted-border": "#d52c364d",
      "--renamed": "#1ca1c7",
      "--renamed-background": "#1ca1c71a",
      "--renamed-border": "#1ca1c74d",
      ...sharedShadcnMapping,
    },
  },
  dark: {
    id: "dark",
    name: "Dark",
    type: "dark",
    tokens: {
      "--background": "#171717",
      "--surface": "#171717",
      "--surface-elevated": "#101010",
      "--editor-background": "#0a0a0a",
      "--app-chrome-background": "#171717",
      "--text": "#fafafa",
      "--text-muted": "#737373",
      "--text-placeholder": "#636363",
      "--text-disabled": "#636363",
      "--text-accent": "#009fff",
      "--icon": "#a3a3a3",
      "--icon-muted": "#737373",
      "--icon-disabled": "#636363",
      "--icon-placeholder": "#636363",
      "--icon-accent": "#009fff",
      "--border": "#1d1d1d",
      "--border-variant": "#262626",
      "--border-focused": "#009fff",
      "--border-selected": "#009fff",
      "--border-disabled": "#262626",
      "--element-background": "#1d1d1d",
      "--element-hover": "#19283c80",
      "--element-active": "#19283cb3",
      "--element-selected": "#19283c99",
      "--element-disabled": "#1d1d1d80",
      "--ghost-element-background": "transparent",
      "--ghost-element-hover": "#19283c59",
      "--ghost-element-active": "#19283c8c",
      "--ghost-element-selected": "#19283c80",
      "--ghost-element-disabled": "transparent",
      "--scrollbar-thumb": "#6363634d",
      "--scrollbar-thumb-hover": "#63636380",
      "--scrollbar-track": "transparent",
      "--error": "#ff2e3f",
      "--error-background": "#ff2e3f1a",
      "--error-border": "#ff2e3f4d",
      "--warning": "#009fff",
      "--warning-background": "#009fff1a",
      "--warning-border": "#009fff4d",
      "--success": "#07c480",
      "--success-background": "#07c4801a",
      "--success-border": "#07c4804d",
      "--info": "#08c0ef",
      "--info-background": "#08c0ef1a",
      "--info-border": "#08c0ef4d",
      "--conflict": "#7b43f8",
      "--conflict-background": "#7b43f81a",
      "--conflict-border": "#7b43f84d",
      "--created": "#07c480",
      "--created-background": "#07c4801a",
      "--created-border": "#07c4804d",
      "--modified": "#009fff",
      "--modified-background": "#009fff1a",
      "--modified-border": "#009fff4d",
      "--deleted": "#ff2e3f",
      "--deleted-background": "#ff2e3f1a",
      "--deleted-border": "#ff2e3f4d",
      "--renamed": "#08c0ef",
      "--renamed-background": "#08c0ef1a",
      "--renamed-border": "#08c0ef4d",
      ...sharedShadcnMapping,
    },
  },
};
